import Head from "next/head";
import { Button } from "@mui/material";
import Typography from "@mui/material/Typography";
import Link from "next/link";

const Home = () => {
  return (
    <>
      <Head>
        <title>Главное меню</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ height: "100vh" }}>
        <div className="container d-flex h-100" style={{ alignItems: "center" }}>
          <div className="mx-auto col-4 border rounded p-4">
            <Link className="w-100 py-3 btn btn-outline-primary" href="/preprocessor">
              Препроцессор
            </Link>
            <Link className="w-100 mt-3 py-3 btn btn-outline-primary" href="/postprocessor">
              Постпроцессор
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
